name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test-api:
    name: Build, Test API, and Send Email
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send Test Email
        env:
          EMAIL: ${{ secrets.EMAIL }} # Ajouter matheothedon@gmail.com comme secret dans GitHub
          PASSWORD: ${{ secrets.PASSWORD }} # Ajouter votre mot de passe d'application Gmail comme secret
        run: python test_qrcode.py

       