services:
  - type: web
    name: api-webshop
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-api
          property: connectionString
      - key: WEBSHOP_API_KEY
        value: ${WEBSHOP_API_KEY}
