name: CI API Webshop

on:
  push:
    paths:
      - 'apimspr/api_webshop/**'
  pull_request:
    paths:
      - 'apimspr/api_webshop/**'
      - '.github/workflows/ci-api-webshop.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apimspr/api_webshop

    env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          WEBSHOP_API_KEY: ${{ secrets.WEBSHOP_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: lancer les tests
        run: |
          PYTHONPATH=./ pytest
