name: CI API Webshop

on:
  push:
    paths:
      - 'apimspr/api_webshop/**'
  pull_request:
    paths:
      - 'apimspr/api_webshop/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apimspr/api_webshop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
