name: CI - API Reseller

on:
  push:
    paths:
      - 'apimspr/apiresellers/**'
      - '.github/workflows/ci-api-reseller.yml'
  pull_request:
    paths:
      - 'apimspr/apiresellers/**'
      

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apimspr/apiresellers

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: installation dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ajouter le dossier app au PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/apimspr/apiresellers/app" >> $GITHUB_ENV

      - name: Lancer les tests Pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/app
          pytest
